### ISSUE TITLE
Idempotent schema/install

### ISSUE THREAD

**Issue by robert-stuttaford** [gfZeng/datomic.schema#1]
Idea: what if `schema/install` was made as idempotent as possible; i.e. preventing unnecessary transaction log entries if all inputs are found to be present already?

This then makes it possible to run an ever-increasing (and sometimes reduced due to refactoring) `install-schema-on-startup!` type script safely; where 'safely' means that no schema changes creates no transactions. 

This is the idea behind http://github.com/rkneufeld/conformity.

Including this feature in this library would make using it a no-brainer, for me :-)

**Comment by spagreeks** [comment]
@robert-stuttaford 
As I know, Datomic support install attributes many times. But it will produce an empty transaction(transact an `tx` entity with no others `tx-data`) if attributes have no change.

Do you mean we should avoid that case?

IMO, that case has no way to absolutely avoid. Considering at this ---- I start two instants of some APP at the same time:
-  If we do not use `transact function`, we can't ensure the consistency for two instants.
- if we use `transact function` to ensure the consistency, aha, we have already created a `transaction`.


BUT

I still think it has worth to avoid transact an empty transaction for many usages.

**Comment by spagreeks** [comment]
release 0.1.9

**Comment by robert-stuttaford** [comment]
Thanks @gfZeng, both for supporting this idea and for your quick turnaround! I'll be trying the library and I'll share feedback as I have it. Nice work! 

Ps. I hope my own library can help you in some small way https://github.com/Cognician/datomic-doc
